# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Mainsail - The 3D Printer Interface
site_url: https://docs.mainsail.xyz
use_directory_urls: true

edit_uri: https://github.com/mainsail-crew/docs/edit/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mainsail-crew
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mainsail
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Mainsail-Crew

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Mainsail:
    - Welcome: index.md

    - Getting Started:
      - Installation:
        - Overview: setup/index.md
        - MainsailOS: setup/mainsailos.md
        - KIAUH: setup/kiauh.md
        - Docker: setup/docker.md
        - Manual setup: setup/manual.md
        - my.mainsail.xyz: setup/mymainsail.md
      - Update:
        - Update Manager: update/update-manager.md
        - Manual Update: update/manual.md
      - Configuration:
        - mainsail.cfg: configuration/mainsail-cfg.md
        - config.json: configuration/config-json.md

    - Overview:
      - Features:
        - Bed Mesh: features/bed-mesh.md
        - Built-in Themes: features/built-in-themes.md
        - Console: features/console.md
        - Custom Themes:
          - Overview: features/custom-themes.md
          - Backgrounds: features/custom-themes/backgrounds.md
          - Community Themes: features/custom-themes/community-themes.md
          - Custom CSS: features/custom-themes/custom-css.md
          - Custom Navigation: features/custom-themes/custom-navigation.md
          - Logos and Icons: features/custom-themes/logos-and-icons.md
        - Dashboard Organisation: features/dashboard-organisation.md
        - Exclude Objects: features/exclude-objects.md
        - Hide Macros, outputs or fans: features/hide-macros-outputs-or-fans.md
        - Localization: features/localization.md
        - Macro Management: features/macro-management.md
        - Macro Prompts: features/macro-prompts.md
        - Presets: features/presets.md
        - Print History and Statistics: features/print-history-and-statistics.md
        - Printer Power Device: features/printer-power-device.md
        - Query devices: features/query-devices.md
        - Thumbnails: features/thumbnails.md
        - Webcams: features/webcams.md
      - Settings:
        - General: settings/general.md
        - Console: settings/console.md
        - Control: settings/control.md
        - Dashboard: settings/dashboard.md
        - Editor: settings/editor.md
        - G-Code Viewer: settings/gcode-viewer.md
        - Heightmap: settings/heightmap.md
        - Macros: settings/macros.md
        - Miscellaneous: settings/miscellaneous.md
        - Navigation: settings/navigation.md
        - Presets: settings/presets.md
        - Printers: settings/printers.md
        - Timelapse: settings/timelapse.md
        - UI-Settings: settings/ui-settings.md
        - Webcams: settings/webcams.md
      - Slicers:
        - Overview: slicers/index.md
        - Cura: slicers/cura.md
        - IdeaMaker: slicers/ideamaker.md
        - OrcaSlicer: slicers/orcaslicer.md
        - PrusaSlicer: slicers/prusaslicer.md

    - Development:
      - Contributing: development/contributing.md
      - Development Setup: development/development-setup.md
      - Localization: development/localization.md

    - FAQ:
      - printer.cfg Snippets: faq/printer-cfg-snippets.md
      - Remote Access: faq/remote-access.md

      - Klipper warnings:
        - Deprecated Options: faq/klipper_warnings/deprecated_options.md
        - Deprecated Values: faq/klipper_warnings/deprecated_values.md
        - Runtime Warnings: faq/klipper_warnings/runtime-warnings.md

      - Klipper errors:
          - MCU Protocol error: faq/klipper_errors/command-format-mismatch.md

      - Moonraker warnings:
        - PolicyKit Permissions: faq/moonraker_warnings/policykit-permissions.md

      - Mainsail errors:
          - Unauthorized: faq/mainsail_errors/connection-unauthorized.md
    - About:
      - Credits: credits.md
      - Data Privacy: data-privacy.md
      - ❤️ Sponsors: sponsors.md

  # subpage for MainsailOS
  - MainsailOS:
    - Overview: mainsailos/index.md

    - Getting started:
      - Raspberry Pi: mainsailos/getting-started/raspberry-pi.md
      - Armbian: mainsailos/getting-started/armbian.md
      - First Boot: mainsailos/getting-started/first-boot.md

    - FAQ:
      - Change WiFi credentials: mainsailos/faq/change-wifi-credentials.md
      - Enable Bluetooth on RPi: mainsailos/faq/enable-bluetooth-on-rpi.md

  # subpage for Crowsnest
  - Crowsnest:
    - Overview: crowsnest/index.md

    - Setup:
      - Installation: crowsnest/setup/installation.md
      - Uninstall: crowsnest/setup/uninstall.md

    - Configuration:
      - '[crowsnest] section': crowsnest/configuration/crowsnest-section.md
      - '[cam] section': crowsnest/configuration/cam-section.md

    - FAQ:
      - Backends: crowsnest/faq/backends.md
      - Clean Log: crowsnest/faq/clean-log.md
      - Common Issues: crowsnest/faq/common-issues.md
      - How to set up Raspicam?: crowsnest/faq/how-to-set-up-raspicam.md
      - How to use WYZE-Cams?: crowsnest/faq/how-to-use-wyze-cams.md
      - Upgrade from v4 to v5: crowsnest/faq/upgrade-from-v4-to-v5.md
      - WebRTC: crowsnest/faq/webrtc.md

  # subpage for Sonar
  - Sonar:
    - Overview: sonar/index.md
    - Installation: sonar/installation.md
    - Configuration: sonar/configuration.md

  # subpage Getting Help
  - Getting Help:
    - Overview: getting-help/index.md
    - Discord: getting-help/discord.md
    - GitHub Discussions: getting-help/github-discussions.md
    - Reddit: getting-help/reddit.md

#plugins:
  # TODO: Zensical will natively support git-related plugins
  #- git-revision-date-localized:
  #    enable_creation_date: true
  #    exclude:
  #      - index.md
  #    fallback_to_build_date: false
  #    locale: en
  #    type: timeago
  #
  # TODO: Zensical will natively support git-related plugins
  #- git-committers:
  #    branch: mkdocs
  #    enabled: !ENV [CI, false]
  #    exclude:
  #      - index.md
  #    repository: mainsail-crew/docs
  #
  # TODO: Check glightbox compatibility with Zensical
  #- glightbox
  #
  # TODO: Social cards not yet configured
  #- social:
  #    cards_layout_dir: layouts
  #    cards_layout: social-card
  #    debug: true

repo_name: mainsail-crew/mainsail
repo_url: https://github.com/mainsail-crew/mainsail

theme:
  favicon: assets/favicon.png
  features:
    - content.action.edit
    - content.code.copy
    - navigation.path
    - navigation.sections
    - navigation.tabs
  icon:
    repo: fontawesome/brands/git-alt
  language: en
  logo: assets/logo.svg
  name: material
  palette:
    scheme: slate
    primary: black
    accent: red

extra_css:
  - stylesheets/extra.css
